name: multijob-workflow

on: push
jobs:
    build:
        runs-on: ununtu-latest
        steps:
            -  name: Build stage
               run: echo"you application start building"
    Test:
        runs-on: ununtu-latest
        steps:
            -  name: Test stage
               run: echo"Test cases are running"
    Deploy:
        runs-on: ununtu-latest
        steps:
            -  name: Deploy stage
               run: echo"Deploying your application"